/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.felit.avro;

@SuppressWarnings("all")
/** This is a message. */
@org.apache.avro.specific.AvroGenerated
public interface UserProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProtocol\",\"namespace\":\"com.felit.avro\",\"doc\":\"This is a message.\",\"name\":\"HelloWorld\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]}],\"messages\":{\"sayHello\":{\"doc\":\"say Hello to manbers\",\"request\":[{\"name\":\"name\",\"type\":\"string\"}],\"response\":\"User\"}}}");
  /**
   * say Hello to manbers
   */
  com.felit.avro.User sayHello(java.lang.CharSequence name) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** This is a message. */
  public interface Callback extends UserProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.felit.avro.UserProtocol.PROTOCOL;
    /**
     * say Hello to manbers
     * @throws java.io.IOException The async call could not be completed.
     */
    void sayHello(java.lang.CharSequence name, org.apache.avro.ipc.Callback<com.felit.avro.User> callback) throws java.io.IOException;
  }
}